#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/bonaparte911/osemu
  # -- image tag
  tag: v732
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more parameters in the [osemu documentation](https://github.com/oscam-emu/OSEmu/blob/master/README).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Set the user [REQUIRED]
  OSEMU_USER: user
  # -- Set the password [REQUIRED]
  OSEMU_PASSWORD: password

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      cs357x:
        port: 11000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: custom
    volumeSpec:
      configMap:
        name: osemu-softcamkey
    subPath:
      - path: softCamKey
        mountPath: /config/SoftCam.Key
        readOnly: true
        enabled: true

softCamKey: |
  #*#*#*#*#*#*#*#*#*#*# KEYS #*#*#*#*#*#*#*#*#*#*#
