apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
{{- /* Fetch configs */ -}}
{{- range $subpath := .Values.persistence.config.subPath -}}
  {{ if $subpath.enabled }}
    {{ $subpath.path }}: |-
      {{ tpl $subpath.config $ | b64enc }}
  {{- end}}
{{- end }}
