#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/bonaparte911/openvscode-julia-cuda
  # -- image tag
  tag: v11.6.2-cudnn8-devel-ubuntu20.04-1.7.3-1.68.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables and parameters in the
# corresponding documentations of [openvscode](https://github.com/gitpod-io/openvscode-server),
# [Julia](https://docs.julialang.org/en/v1/manual/environment-variables/) and
# [cuda](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Security token for accessing the Web UI. [OPTIONAL]
  CONNECTION_TOKEN:
  # -- Path to a file (ie. /path/to/file) inside the container that contains the security token that overrides CONNECTION_TOKEN. [OPTIONAL]
  CONNECTION_SECRET:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
  config:
    enabled: true
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
